name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build vid-node
        run: make build